### ISSUE TITLE
Fails on gnome 42.4

### ISSUE THREAD

**Issue by lonix1** [tuberry/extension-list#12]
Just installed ubuntu 22.04
Gnome 42.4

Icon shows in panel, but nothing happens when clicking it. Anything I can do on my side, or is this a compatibility issue?

**Comment by lonix1** [comment]
Restarted and it's working! Thanks.

**Comment by tuberry** [comment]
Any logs? 
```bash
journalctl -fo cat /usr/bin/gnome-shell
```

**Comment by tuberry** [comment]
There seems to be no relevant information, try re-enabling this extension to see if logs are printed.

You can also try installing it from GitHub to see if there are still problems.
