### ISSUE TITLE
where to learn

### ISSUE THREAD

**Issue by Fsouza1997** [tuberry/extension-list#16]
hello, could you help me, I would like to learn how to develop my own extensions for gnome shell and I would like to know where I can study about

**Comment by tuberry** [comment]
Sorry for late.

Here's a [step-by-step tutorial](https://gjs.guide/extensions/) that I wish I had read when I started.
You may also need the [gjs documentation](https://gjs-docs.gnome.org/) and the [source code](https://github.com/GNOME/gnome-shell/tree/main/js) for the gnome shell.
Referencing existing extensions that have similar functionality to that expected is probably a good place to start.

Hope this helps. Happy coding!

**Comment by Fsouza1997** [comment]
desculpa a demora.
obrigado. na verdade já tinha lido parte desses documentos.

**Comment by ghxstbox** [comment]
@tuberry Thanks for linking the thread. Out of curiosity, can elements from D3 and other such libraries be implemented into gnome extensions, or is the GJS framework fundamentally different in such a way that it doesn't integrate with with a library such as D3.j or Chart.js? I want to make some data visualization statistics that are integrated into the main desktop window UI as I have a fair bit of experience in D3!

**Comment by tuberry** [comment]
>  is the GJS framework fundamentally different in such a way that it doesn't integrate with with a library such as D3.j or Chart.js?

You could use web JS libraries via WebKit-GTK like [foliate](https://github.com/johnfactotum/foliate), but unfortunately the GNOME Shell UI doesn't use GTK.

>  can elements from D3 and other such libraries be implemented into gnome extensions,

[Cairo](https://www.cairographics.org/tutorial/), used by [Clutter](https://gjs.guide/extensions/overview/architecture.html#clutter-and-st) and often abbreviated as [cr](https://github.com/search?q=repo%3AGNOME%2Fgnome-shell+cr.+language%3AJavaScript&type=code) in codes, might be your best bet for drawing 2D shapes here.

By the way, you could ask extension reviewers and more experienced extension developers for help directly in the [official matrix room](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#getting-help).

**Comment by ghxstbox** [comment]
> @ghxstbox
> 
> > is the GJS framework fundamentally different in such a way that it doesn't integrate with with a library such as D3.j or Chart.js?
> 
> You could use web JS libraries via WebKit-GTK like [foliate](https://github.com/johnfactotum/foliate), but unfortunately the GNOME Shell UI doesn't use GTK.
> 
> > can elements from D3 and other such libraries be implemented into gnome extensions,
> 
> [Cairo](https://www.cairographics.org/tutorial/), used by [Clutter](https://gjs.guide/extensions/overview/architecture.html#clutter-and-st) and often abbreviated as [cr](https://github.com/search?q=repo%3AGNOME%2Fgnome-shell+cr.+language%3AJavaScript&type=code) in codes, might be your best bet for drawing 2D shapes here.
> 
> By the way, you could ask extension reviewers and more experienced extension developers for help directly in the [official matrix room](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#getting-help).

Thanks so much! I wanted to ask if you might have had any experience programming in KDE? I wam trying to figure out which platform to invest some time into learning the programming utilities and I am *slightly* disappointed with how complicated the QML interface is...:(

Was wondering if you might be familiar with the javascript scripting features of KDE applciations, and if they are of similar complexity to that of GNOME's scripting framework? Thanks!

**Comment by tuberry** [comment]
> I wanted to ask if you might have had any experience programming in KDE?

Sorry, nope.

>  you might be familiar with the javascript scripting features of KDE applciations, and if they are of similar complexity to that of GNOME's scripting framework? 

Still nope.
