### ISSUE TITLE
Default to gnome-extensions-app and fallback to extensions.gnome.org

### ISSUE THREAD

**Issue by hackerb9** [tuberry/extension-list#19]
Please consider changing the behaviour of clicking on the Extension icon on the toolbar to run `gnome-extensions-app` and only launch a browser to visit extensions.gnome.org if the app is not found. Thanks, again!

**Comment by tuberry** [comment]
I think `extensions.gnome.org` is more feature-rich than `gnome-extensions-app`. Shouldn't it be the preferred option?
