### ISSUE TITLE
gnome-extension-apps 

### ISSUE THREAD

**Issue by galen1423** [tuberry/extension-list#2]
Hi

Thanks for your very useful extension (+1 for icon in top panel too... :) ).

Speak of icon, when I click her in the menu, I have a error message : 
« gnome-extensions-app not found »

I have changed **gnome-extensions-apps** to **gnome-shell-extension-prefs** in **extension.js** file at line 80 and now, extension prefs are launch as expected.
I use Ubuntu 20.04 & 20.10

Thx again.

**Comment by tuberry** [comment]
It seems that `gnome-shell-extension-prefs` is deprecated and `gnome-extensions-app` is not in common use (? I am not sure). By the way, I don't have a Ubuntu env right now. Could you try changing the line to:
```js
addButtonItem('application-x-addon-symbolic', () => { item._getTopMenu().close(); Shell.AppSystem.get_default().lookup_app('org.gnome.Extensions.desktop').activate(); });

``` 
and give me feedback. Thanks! I think it will function in any distros.

**Comment by galen1423** [comment]
Hi,

As requested, I add your line and it work. :)

**Comment by tuberry** [comment]
Thanks.
