### ISSUE TITLE
Not working on Ubuntu 24.04 (Gnome 46)

### ISSUE THREAD

**Issue by fernandovmacedo** [tuberry/extension-list#25]
I have tried installing it in Ubuntu 24.04 beta on Gnome 46 and got the following error message:

The settings of extension extension-list@tu.berry had an error:
```
Error: Requiring Json, version none: Typelib file for namespace 'Json' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Json/:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```

EDIT: I have installed some JSON packages, and now it is working. It is not clear what are the missing dependencies on Ubuntu 24.04.

**Comment by tuberry** [comment]
The dependency on `json-glib` was dropped in the latest commit, you can try to install the extension from [Github](https://github.com/tuberry/extension-list?tab=readme-ov-file#manual) and uninstall the JSON package you installed then re-login to see if it works. :)
