### ISSUE TITLE
I cannot install

### ISSUE THREAD

**Issue by RoyTheNewbie** [tuberry/extension-list#26]
I am not a computer expert so please forgive any naivete on my part.
I am using Ubuntu 22.04. I had a major problem with an upgrade a couple of days ago and after lots of frustration managed to reinstall the OS.
Previously I had been using extension-list . However, now when I try to install it I get an error message, saying I don't have a needed app.
I have attached a screenshot.
Please can you advise me on this? Thank you.
![Screenshot 2024-05-11 at 11-26-32 Extension List - GNOME Shell Extensions](https://github.com/tuberry/extension-list/assets/27382017/7d3b2916-956f-48c8-9928-6dd0ca86e14e)

**Comment by tuberry** [comment]
Referring to this [answer](https://askubuntu.com/a/1404507), `chrome-gnome-shell` should be installed firstly:

```
sudo apt install chrome-gnome-shell
```
