### ISSUE TITLE
Bug with G.S 42 

### ISSUE THREAD

**Issue by galen1423** [tuberry/extension-list#9]
Hi,

O.S: Ubuntu Jammy Jellyfish (22.04 development branch)
G.S: 42

extension-list version : 30

`JS ERROR: Extension extension-list@tu.berry: TypeError: ExtManager.connectObject is not a function`

**Comment by tuberry** [comment]
It's introduced by [upstream](https://github.com/GNOME/gnome-shell/commit/26235bbe5433c48b81bd3917aaf9ef14ff1929b2) 20 days ago. Maybe the gnome-shell on your system has not been updated to the latest release.
